version: "3.9"

services:
  fullstack:
    build:
      context: .
    image: full-ros2-stack
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=102
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "4200:4200"
