version: "3.9"

services:
  robot:
    build:
      context: ./robot   
    image: my-ros2-gazebo
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=102
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  server:
    build:
      context: ./server
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=102

  client:
    build:
      context: ./client
    ports:
      - "4200:4200"

